# Generated by Django 5.2.5 on 2025-11-05 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('web_search', 'Web Search'), ('discord_webhook', 'Discord Webhook'), ('slack_webhook', 'Slack Webhook'), ('teams_webhook', 'Microsoft Teams Webhook')], max_length=50)),
                ('encrypted_access_token', models.TextField()),
                ('encrypted_refresh_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'credential_type')},
            },
        ),
    ]
