# Generated by Django 5.2.5 on 2025-11-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredential',
            name='credential_type',
            field=models.CharField(choices=[('web_search', 'Web Search'), ('discord_webhook', 'Discord Webhook'), ('slack_webhook', 'Slack Webhook'), ('teams_webhook', 'Microsoft Teams Webhook'), ('gmail', 'Google Mail')], max_length=50),
        ),
    ]
