# Generated by Django 5.2.5 on 2025-12-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='logs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
