# Generated by Django 5.2.5 on 2025-09-08 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='configuration',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for the tool.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='function_schema',
            field=models.JSONField(blank=True, default=dict, help_text="JSON schema defining the tool's input parameters."),
        ),
        migrations.AddField(
            model_name='tool',
            name='implementation_class',
            field=models.CharField(blank=True, help_text='Class name if the tool function is within a class.', max_length=255),
        ),
        migrations.AddField(
            model_name='tool',
            name='implementation_module',
            field=models.CharField(blank=True, help_text="Python module path where the tool's function is implemented.", max_length=255),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the tool is active and can be used by agents.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_type',
            field=models.CharField(choices=[('web_search', 'Web Search'), ('custom', 'Custom')], default='custom', max_length=50),
        ),
    ]
