# Generated by Django 5.2.5 on 2025-10-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0002_tool_configuration_tool_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tool",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="tool",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="function_schema",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="implementation_class",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="implementation_module",
        ),
        migrations.AddField(
            model_name="tool",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Tool-specific configuration. For web_search: {'api_key': '...', 'max_results': 5}",
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="description",
            field=models.TextField(
                help_text="Description for the LLM to understand when and how to use this tool."
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="name",
            field=models.CharField(
                help_text="Unique identifier for the tool (e.g., 'tavily_search', 'brave_search')",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="tool_type",
            field=models.CharField(
                choices=[("web_search", "Web Search")],
                default="web_search",
                max_length=50,
            ),
        ),
    ]
