# Generated by Django 5.2.5 on 2025-11-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_tool_options_remove_tool_configuration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_type',
            field=models.CharField(choices=[('web_search', 'Web Search'), ('discord_webhook', 'Discord Webhook'), ('slack_webhook', 'Slack Webhook'), ('teams_webhook', 'Microsoft Teams Webhook')], default='web_search', max_length=50),
        ),
    ]
