# Generated by Django 5.2.5 on 2025-11-11 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_tool_tool_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(help_text="Unique identifier for the tool (e.g., 'tavily_search', 'brave_search')", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tool',
            unique_together={('user', 'name')},
        ),
    ]
