# Generated by Django 5.2.5 on 2025-11-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_tool_user_alter_tool_name_alter_tool_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_type',
            field=models.CharField(choices=[('web_search', 'Web Search'), ('discord_webhook', 'Discord Webhook'), ('slack_webhook', 'Slack Webhook'), ('teams_webhook', 'Microsoft Teams Webhook'), ('gmail', 'Google Mail')], default='web_search', max_length=50),
        ),
    ]
