# Generated by Django 5.2.5 on 2025-12-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0006_alter_tool_tool_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="mcp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name="tool",
            name="tool_type",
            field=models.CharField(
                choices=[
                    ("web_search", "Web Search"),
                    ("discord_webhook", "Discord Webhook"),
                    ("slack_webhook", "Slack Webhook"),
                    ("teams_webhook", "Microsoft Teams Webhook"),
                    ("gmail", "Google Mail"),
                    ("postgres", "PostgreSQL Database"),
                ],
                default="web_search",
                max_length=50,
            ),
        ),
    ]
