# Generated by Django 5.2.5 on 2025-08-28 02:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The function name for the tool.', max_length=100, unique=True)),
                ('description', models.TextField(help_text="Description for the LLM to understand the tool's purpose.")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('graph_data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text="A description of the agent's role and capabilities.")),
                ('system_instruction_prompt', models.TextField()),
                ('role', models.CharField(choices=[('general', 'General'), ('supervisor', 'Supervisor')], default='general', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible JSON field for role-specific data.')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('custom', 'Custom')], default='openai', max_length=50)),
                ('model', models.CharField(default='gpt-4o', help_text="e.g., 'gpt-4o', 'claude-3-opus-20240229'", max_length=100)),
                ('api_key', models.CharField(blank=True, help_text="API key for the agent's provider. Leave blank to use environment variables.", max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.project')),
                ('tools', models.ManyToManyField(blank=True, related_name='agents', to='core.tool')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
    ]
