# Generated by Django 5.2.5 on 2025-08-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='api_config',
            field=models.JSONField(blank=True, default=dict, help_text='Configuration for API tools (URL, method, headers, etc.)'),
        ),
        migrations.AddField(
            model_name='tool',
            name='path',
            field=models.CharField(blank=True, help_text="Import path for Built-in tools'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_type',
            field=models.CharField(choices=[('BUILT_IN', 'Built-in Tool'), ('API', 'API Tool')], default='BUILT_IN', max_length=20),
        ),
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
