# Generated by Django 5.2.5 on 2025-08-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tool_api_config_tool_path_tool_tool_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], default='openai', max_length=50),
        ),
    ]
