# Generated by Django 5.2.5 on 2025-08-29 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_agent_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tool',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If true, this tool is available to all users.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agent',
            name='api_key',
            field=models.CharField(blank=True, help_text='Project-specific API key. Leave blank to use environment variables.', max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Project-specific data, e.g., node position on the canvas.'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='model',
            field=models.CharField(default='gpt-4o', max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='AgentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, help_text='If true, this agent template is available to all users.')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('system_instruction_prompt', models.TextField()),
                ('role', models.CharField(choices=[('general', 'General'), ('supervisor', 'Supervisor')], default='general', max_length=50)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], default='openai', max_length=50)),
                ('model', models.CharField(default='gpt-4o', max_length=100)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_templates', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(blank=True, related_name='owned_agent_templates', to=settings.AUTH_USER_MODEL)),
                ('tools', models.ManyToManyField(blank=True, related_name='agent_templates', to='core.tool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='template',
            field=models.ForeignKey(blank=True, help_text='The template this agent was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agenttemplate'),
        ),
    ]
