name: ensemble-django-backend

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - ../.env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
