# Generated by Django 5.2.5 on 2025-09-04 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text="A description of the agent's role and capabilities.")),
                ('system_instruction_prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('general', 'General'), ('supervisor', 'Supervisor')], default='general', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible JSON field for role-specific data.')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google'), ('custom', 'Custom')], default='openai', max_length=50)),
                ('model', models.CharField(default='gpt-4o', help_text="e.g., 'gpt-4o', 'claude-3-opus-20240229'", max_length=100)),
                ('api_key', models.CharField(blank=True, help_text="API key for the agent's provider. Leave blank to use environment variables.", max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='graph.graph')),
                ('tools', models.ManyToManyField(blank=True, related_name='agents', to='tools.tool')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
    ]
