# Generated by Django 5.2.5 on 2025-12-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_alter_agent_unique_together_agent_user_and_more"),
        ("tools", "0007_mcp_alter_tool_tool_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="mcp",
            field=models.ManyToManyField(
                blank=True, related_name="agents", to="tools.mcp"
            ),
        ),
    ]
